# -*- coding: utf-8 -*-
"""9may.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZBvLAkSUauab8kSwOMbHK1pij3PyXyPA
"""

x=10
y=19
if(x<=10 and y>=18):
    print("age is vailid")
else:
      print("age is invailid")

a=1
b=7
c=10
if(a<b and b<c):
    print("a  minimum")
elif(b<c and a<c ):
     print("b is minimum")
else:
     print("c is minimum")

a=97

if(a>=60 and a<=75 ):
    print("average")
elif(a>=75 and a<=85 ):
     print("good")
elif(a>=85 and a<=95):
     print("exillent")
elif(a>=95 and a<=100):
    print("brilliant")
else:
      print("fail")

a=7

if(a==1 ):
    print("jan")
elif(a==2  ):
     print("fab")
elif(a==3 ):
     print("march ")
elif(a==4 ):
    print("april")
elif(a==5):
      print("may")
elif(a==6):
    print("june")
elif(a==7):
    print("july")
elif(a==8 ):
     print("aug ")
elif(a==9 ):
    print("sep")
elif(a==10):
      print("oct")
elif(a==11):
    print("nav")
elif(a==12):
    print("dec")
 else:
      print("miss match")

a=10
if(a<=5and a>=0 ):
    print("a is minimum")
elif(a<=10 and a>=5):
  print("b is minimum")
elif(a<=15 and a>=10):
  print("c is minimum")
else:
    print("miss match")

a=6
if(a%2==0 and a%3==0):
    print("a is dividable by 6")
else:
    print("a is not dividable by 6")

# Take a variable with any value
number = int(input("Enter a number: "))

# Check if the number is divisible by 6
if number % 2 == 0 and number % 3 == 0:
    print(" number is divisible by 6")
else:
    print(" number is not divisible by 6")

